[package]
name = "gw_db"
version = "0.1.0"
edition = "2021"

[dependencies]
gw_core = { path = "../gw_core" }
tracing = "0.1.41"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros", "derive" ] }
tokio = { version = "1.43.0", features = ["macros"] }
